### ISSUE TITLE
labels on this repo?

### ISSUE THREAD

**Issue by wburningham** [paketo-buildpacks/ca-certificates#18]
## What happened?

* What were you attempting to do?

Attempting to find non-language family buildpacks on github by searching repos with the `cnb` and `all-applications`.

* What did you expect to happen?

I expected this repo to show up.

Am I in correct or should this repo have the `cnb` and `all-applications` labels?

**Comment by ekcasey** [comment]
Thanks for pointing this out! I added the labels to the repo. Sorry About the slow response :)
