### ISSUE TITLE
Allow users to opt out of the CA Certificates buildpack

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/ca-certificates#32]
## What happened?

* What were you attempting to do?

`pack build` a Node.js application with no CA Certificates (the Node.js language family buildpack has CA Certificates buildpack as an optional order group in the `buildpack.toml`)

* What did you expect to happen?

I initially would've expected build output that only contained logs from `node-engine`, `yarn-install', `yarn`, and `yarn-start`.

* What was the actual behavior? Please provide log output, if possible.

The build output contained logs from the `CA Certificates buildpack`, which was misleading since I didn't want to use CA certificates with my app.

Users should have an option to opt out of using the CA certificate buildpack all together. The default behaviour is to always detect, but users should have an option to turn this behaviour off if they know they won't need it.

I'm in agreement that the [current behaviour](https://github.com/paketo-buildpacks/ca-certificates/blob/5164ed35c28f957a0488f78e33b1217f13ca49b4/cacerts/detect.go#L34-L36) where the buildpack always detects is something we should keep, because as @ekcasey has said, it allows certificates to be dynamically added at runtime without having to specify anything at build time.

The issue lies in the fact that some users may not want CA certificates at all, and have no simple way to turn this behaviour off. This clutters logs with CA Certificate buildpack output, and also  unnecessarily creates a layer when a user knows they won't want CA certificates.

I propose some new environment variable (such as `BP_CA_CERTS_LAUNCH`) that can be set to false at build-time if a user does not want the buildpack to detect. The default will be true, and the buildpack will proceed normally in this case.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [X] I have included steps for reproduction.

**Comment by sophiewigmore** [comment]
Follow up from @ekcasey :

> Maybe we can change this to something like `BP_CA_CERTS_LAUNCH_HELPER`. I am thinking about the situation where a binding with certs is provided at build time but the user doesn't want to pay the startup cost of runtime the cert helper at launch time. If we changed this flag to be launch-specific we could address the need you raise by failing detection if both:
> 1. there is no binding of type `ca-certificates` at build-time
> 2. `BP_CA_CERTS_LAUNCH_HELPER=false`
> 
> while also meeting a potential need for build-only ca cert support.
> 
_Originally posted by @ekcasey in https://github.com/paketo-buildpacks/ca-certificates/pull/31#discussion_r593435076_

**Comment by sophiewigmore** [comment]
I see your point. I don't love the `HELPER` part because, it makes it wordier and implies a user knows about the helper layer that gets created. In the case where a user just wants this feature off, I wouldn't bet that they'd know about the helper. I'd prefer something like `BP_CA_CERTS_LAUNCH`=false

**Comment by ekcasey** [comment]
I worry that `BP_CA_CERTS_LAUNCH` could be interpreted to mean "add these certs to final image so they are available at launch". I think that, to understand the workflow, users need to be aware of the launch helper and know that it processes the bindings at runtime.

**Comment by sophiewigmore** [comment]
Following the Paketo working group meeting 3/17:
A suggestion was to name the environment variable something that focuses on enabling/disabling the behaviour as a whole, rather than the underlying processes that take care of this. Something like `BP_ALLOW_CA_CERTS_AT_LAUNCH`or`BP_ENABLE_RUNTIME_CERT_BINDING`.

**Comment by anderius** [comment]
That would be nice! I use read-only containers, and the runtime binding fails due to that. Disabling just the runtime binding would be perfect.

**Comment by ekcasey** [comment]
@anderius If you don't need additional certs at runtime it won't matter to, but just in case it's useful to you or someone else.. It's worth noting that the buildpack only writes in `$TMPDIR`. So you could mount a tmpfs to `$TMPDIR` and keep the root filesystem read-only if you wish.

**Comment by anderius** [comment]
@ekcasey Thank you for that information. My /tmp is indeed writable, but it was the bellsoft-liberica builder that caused the error I was experiencing during startup. It tries to import system certificates into the jvm truststore at runtime.

When it works, it looks like this: "Adding 129 container CA certificates to JVM truststore".

I don't want to have my JVM truststore writeable, so I will look for a way to configure that builder instead.

**Comment by dmikusa-pivotal** [comment]
Do you have an example build output where it fails?

At least with the JVM buildpacks, it should check if the keystore is writable and output a warning message if it's not. That also should skip writing anything. See [here](https://github.com/paketo-buildpacks/libjvm/blob/main/certificate_loader.go#L198).

>"WARNING: Unable to add container CA certificates to JVM because %s is read-only"

Thanks

**Comment by anderius** [comment]
@dmikusa-pivotal You are correct, it logs at warning when it fails. I was trying to get rid of that warning message.

**Comment by RobbyRabbitman** [comment]
How to disable CA certificates at build time?
